#################
### AUTOSTART ###
#################

#exec-once = [workspace 10 silent] kitty -e btop

exec-once = sleep 1 && $terminal -e cava
exec-once = sleep 1 && $terminal --hold fastfetch
exec-once = sleep 1 && $terminal -e cmatrix

exec-once = ~/.config/waybar/scripts/launch.sh
exec-once = hyprpaper

exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

exec-once = wl-clip-persist --clipboard regular

exec-once = sleep 1 && brightnessctl --device='tpacpi::kbd_backlight' set 100%
